on:
  push:
    branches:
      - master
      - develop
      - main

env:
  ACTIVE_API_URL: "https://aigtest.nnsworkshop.com/active"
  ACTIVE_REGISTRY_URL: "us-central1-docker.pkg.dev/noname-artifacts/nns-docker"

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run CrAPI 
        run: |
          docker compose pull
          docker compose -f docker-compose.yml --compatibility up -d
        
      - name: Test if CrAPI is up
        run: sleep 5 && curl http://localhost --retry 10 --retry-delay 1 

      - name: setup node dependencies for adding users
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      #- name: Add users to CrAPI
      #  run: |
       #   npm install
      #    node .
      #  working-directory: noname/baseline-script

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ACTIVE_REGISTRY_URL }}
          username: ${{ secrets.ACTIVE_REGISTRY_USER }}
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: Active Testing Scan
        run: >
          docker run
          --add-host=host.docker.internal:host-gateway
          -e ACTIVE_CONFIG_FILE_PATH=/noname/active-config.json 
          -v $(pwd)/noname:/noname 
          -v $(pwd)/openapi-spec:/openapi-spec 
          ${{ env.ACTIVE_REGISTRY_URL }}/active-cli:2.19.0 scan
          --api-url=${{ secrets.ACTIVE_API_URL }}
          --api-token=${{ secrets.ACTIVE_API_TOKEN }}
          --test-group-id=6767cf71-754f-4119-85a0-7497931b1198
          --branch-name=${{ github.head_ref || github.ref_name }}
          --severity-threshold=none

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Security scan passed, deploying to production
